; Konfigurasi PlatformIO untuk STM32_05_DAC_RTOS_Output
; STM32F103C8 has DAC, STM32F401/411 don't have DAC

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
monitor_speed = 115200
extra_scripts = 
    pre:extra_script_F103.py
    pre:extra_script_freertos.py
build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32F103xB
    -DFREERTOS
    -include include/FreeRTOSConfig.h
    -Iinclude
upload_protocol = stlink
