[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags = 
    -DCONFIG_ESP32_DEFAULT_CPU_FREQ_240=1
    -DCONFIG_ETH_USE_SPI_ETHERNET=1
    -DCONFIG_ETH_SPI_ETHERNET_W5500=1
