[platformio]
name = P10 — Matrix Commander  : Pemindaian Keypad 4×4 & Tampilan LCD

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
upload_protocol = stlink
; upload_flags = -c set CPUTAPID 0x2ba01477
