; ============================================================================
; PlatformIO Configuration - STM32_01_Task_Create_Basic
; FreeRTOS Basic Task Creation pada STM32F103 (Blue Pill)
; ============================================================================

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
extra_scripts = pre:extra_script_F103.py
build_flags = 
    -D USE_HAL_DRIVER
    -D STM32F103xB
    -D HSE_VALUE=8000000
    -I src
    -I include
    -Wno-unused-variable
    -Wno-unused-function
