; PlatformIO Project Configuration
; P04: Push Button Pull-Down Resistor Eksternal

[platformio]
default_envs = bluepill_f103c8

[env:bluepill_f103c8]
platform = ststm32
board = genericSTM32F103C8
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
build_flags =
    -D USE_HAL_DRIVER
    -D STM32F103xC
    -D HSE_VALUE=8000000
    -I include
