[env:esp32dev]
platform = espressif32
framework = espidf
board = esp32dev
monitor_speed = 115200
board_build.sdkconfig = sdkconfig.esp32dev

[env:lolin_s2]
platform = espressif32
framework = espidf
board = lolin_s2_mini
monitor_speed = 115200
board_build.sdkconfig = sdkconfig.lolin_s2

[env:esp32s3]
platform = espressif32
framework = espidf
board = esp32-s3-devkitm-1
monitor_speed = 115200
board_build.sdkconfig = sdkconfig.esp32s3
