[platformio]
name = P06 — Force Field       : Pull-DOWN Internal & Logika Active-HIGH

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
upload_protocol = stlink
; upload_flags = -c set CPUTAPID 0x2ba01477
