; =============================================================================
; ESP32_13_PWM_LEDC_Fade
; Modul 05 - DAC/PWM | Bonus: Fitur Khusus ESP32
;
; Demonstrasi LEDC Hardware Fade — fade otomatis tanpa CPU
; Fitur ini TIDAK tersedia di STM32 (perlu software/DMA)
; =============================================================================

[env]
framework = espidf
monitor_speed = 115200

[env:esp32dev]
platform = espressif32
board = esp32dev

[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
