; PlatformIO Project Configuration
; Framework: STM32Cube HAL

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
build_flags =
    -D USE_HAL_DRIVER
    -D STM32F103xB
    -D STM32F1
    -D HSE_VALUE=8000000
    -I include

[env:stm32f401cc]
platform = ststm32
board = genericSTM32F401CC
framework = stm32cube
upload_protocol = stlink
monitor_speed = 115200
build_flags =
    -D USE_HAL_DRIVER
    -D STM32F401xC
    -D HSE_VALUE=25000000
    -I include

[env:stm32f411ce]
platform = ststm32
board = genericSTM32F411CE
framework = stm32cube
upload_protocol = stlink
monitor_speed = 115200
build_flags =
    -D USE_HAL_DRIVER
    -D STM32F411xE
    -D HSE_VALUE=25000000
    -I include
