; Program 03: LED Breathing Effect (LEDC PWM)
; ESP-IDF Framework with 3 board variants

[env:esp32-doit]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
build_flags = -D CONFIG_LED_GPIO=2

[env:esp32-s2-lolin]
platform = espressif32
board = lolin_s2_mini
framework = espidf
monitor_speed = 115200
build_flags = -D CONFIG_LED_GPIO=15

[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
build_flags = -D CONFIG_LED_GPIO=48
