; Multi_05_RTOS_Distributed_System - STM32 (SPI Master, bluepill F103C8)
; STM32 node: collect sensor data, log to SD, send to ESP32 hub

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube

extra_scripts =
    pre:extra_script_F103.py
    pre:extra_script_freertos.py

build_flags =
    -DSTM32F103xB
    -DUSE_HAL_DRIVER
    -DHSE_VALUE=8000000
    -IFreeRTOS/Source/include
    -IFreeRTOS/Source/portable/GCC/ARM_CM3
    -Iinclude

monitor_speed = 115200
