; Konfigurasi PlatformIO untuk STM32 SPI SDCard RTOS Queue
[platformio]
default_envs = bluepill_f103c8

[env]
platform = ststm32
framework = stm32cube
monitor_speed = 115200
upload_protocol = stlink
extra_scripts =
    pre:extra_script_F103.py
    pre:extra_script_F4xx.py
    pre:extra_script_freertos.py

build_flags =
    -lm
    -DUSE_HAL_DRIVER
    -DFREERTOS
    -Iinclude

[env:bluepill_f103c8]
board = bluepill_f103c8
build_flags =
    ${env.build_flags}
    -DSTM32F103xB

[env:stm32f401cc]
board = genericSTM32F401CC
build_flags =
    ${env.build_flags}
    -DSTM32F401xC

[env:stm32f411ce]
board = genericSTM32F411CE
build_flags =
    ${env.build_flags}
    -DSTM32F411xE
