[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
lib_deps = 
    arduino-libraries/SD@^1.2.4
monitor_speed = 115200

[env:blackpill_f401cc]
platform = ststm32
board = blackpill_f401cc
framework = arduino
lib_deps = 
    arduino-libraries/SD@^1.2.4
monitor_speed = 115200
