[platformio]
src_dir = main

; Multi_05_RTOS_Distributed_System - ESP32 (Hub Node)
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags =
