[platformio]
name = P05 — Phantom Touch     : Pull-UP Internal & Tombol Tanpa Resistor

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
upload_protocol = stlink
; upload_flags = -c set CPUTAPID 0x2ba01477
