[platformio]
src_dir = main

; Multi_04_RTOS_Queue_Communication - ESP32 (SPI Slave)
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags =
