[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
monitor_speed = 115200
lib_deps = 
    bblanchon/ArduinoJson@^6.21.0
build_flags = -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
