; Konfigurasi PlatformIO untuk STM32 FreeRTOS program
[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
monitor_speed = 115200
extra_scripts = 
    pre:extra_script_F103.py
    pre:extra_script_freertos.py
build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32F103xB
    -DFREERTOS
    -include include/FreeRTOSConfig.h
    -Iinclude
upload_protocol = stlink

[env:stm32f401cc]
platform = ststm32
board = genericSTM32F401CC
framework = stm32cube
monitor_speed = 115200
extra_scripts = 
    pre:extra_script_F4xx.py
    pre:extra_script_freertos.py
build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32F401xC
    -DFREERTOS
    -include include/FreeRTOSConfig.h
    -Iinclude
upload_protocol = stlink

[env:stm32f411ce]
platform = ststm32
board = genericSTM32F411CE
framework = stm32cube
monitor_speed = 115200
extra_scripts = 
    pre:extra_script_F4xx.py
    pre:extra_script_freertos.py
build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32F411xE
    -DFREERTOS
    -include include/FreeRTOSConfig.h
    -Iinclude
upload_protocol = stlink
