; PlatformIO Project Configuration File
; Program 08: DIP Switch Reader
; Platform: ESP32 (ESP-IDF Native Framework)

[env:esp32-doit]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
upload_speed = 921600
build_flags = -D CONFIG_LED_GPIO=2

[env:esp32-s2-lolin]
platform = espressif32
board = lolin_s2_mini
framework = espidf
monitor_speed = 115200
build_flags = -D CONFIG_LED_GPIO=15

[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
build_flags = -D CONFIG_LED_GPIO=48
