[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube

upload_protocol = stlink
debug_tool = stlink

monitor_speed = 115200

build_flags = 
    -DUSE_HAL_DRIVER
    -DSTM32F103xB
    -I include

lib_deps = 
