; =============================================================================
; ESP32_13_ADC_Attenuation_WiFi
; Modul 04 - ADC | Bonus: Fitur Khusus ESP32
;
; Demonstrasi ADC Attenuation Control dan konflik ADC2+WiFi
; Fitur ini TIDAK tersedia di STM32
; =============================================================================

[env]
framework = espidf
monitor_speed = 115200

[env:esp32dev]
platform = espressif32
board = esp32dev

[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
