; PlatformIO Project Configuration
; Modul 04 - ADC | ADC Calibration
; Framework: ESP-IDF

[platformio]
default_envs = esp32dev

[env]
platform = espressif32
framework = espidf
monitor_speed = 115200
build_flags = 
    -DLOG_LOCAL_LEVEL=ESP_LOG_INFO

[env:esp32dev]
board = esp32dev

[env:lolin_s2_mini]
board = lolin_s2_mini

[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1
