; PlatformIO Project Configuration
; Modul 05 - DAC & PWM | PWM LED Brightness
; Framework: STM32Cube HAL

[platformio]
default_envs = bluepill_f103c8

[env]
platform = ststm32
framework = stm32cube
monitor_speed = 115200
upload_protocol = stlink
debug_tool = stlink
build_flags = -DUSE_HAL_DRIVER

[env:bluepill_f103c8]
board = bluepill_f103c8

[env:genericSTM32F401CC]
board = genericSTM32F401CC

[env:genericSTM32F411CE]
board = genericSTM32F411CE
