[env:stm32f411ce]
platform = ststm32
board = blackpill_f411ce
framework = stm32cube
upload_protocol = dfu
upload_speed = 115200
monitor_speed = 115200
monitor_port = /dev/ttyUSB0
build_flags = 
    -DSTM32F411xE
    -O2
lib_deps =
debug_tool = stlink
