[platformio]
; default_envs = f103
; default_envs = f401
default_envs = f411

[env:f103]
platform = ststm32
board = genericSTM32F103C8
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
build_flags = 
    -D USE_HAL_DRIVER
    -D STM32F103xC
    -D HSE_VALUE=8000000
    -I include

[env:f401]
platform = ststm32
board = genericSTM32F401CC
framework = stm32cube
upload_protocol = stlink
monitor_speed = 115200
build_flags = 
    -D USE_HAL_DRIVER
    -D STM32F401xC
    -D HSE_VALUE=25000000
    -I include

[env:f411]
platform = ststm32
board = genericSTM32F411CE
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
build_flags = 
    -D USE_HAL_DRIVER
    -D STM32F411xE
    -D HSE_VALUE=25000000
    -I include
